### ISSUE TITLE
Can't run example code

### ISSUE THREAD

**Issue by LucaFranceschini** [ajvincent/es-membrane#147]
I tried to run [the example code from the readme](https://github.com/ajvincent/es-membrane#how-to-use-the-es-membrane-module) (avoiding boolean arguments) but it fails with the following error as soon as it calls `getHandlerByName`:

    TypeError: Cannot read property 'fieldName' of undefined
      at MembraneInternal.convertArgumentToProxy (node_modules/es7-membrane/docs/dist/node/es7-membrane.js:918:21)

This happens no matter what the third argument of `convertArgumentToProxy` is. My understanding is that this argument is the (wet) object I want inside the membrane, is it correct?

I must be missing something obvious here.

**Comment by ajvincent** [comment]
Heh, whoops!  What happened is that wetDocument itself is undefined, which is why it's throwing an error.  You should define what wetDocument is first.

**Comment by LucaFranceschini** [comment]
Hi, thanks for help.

I am using actual objects in place of `wetDocument` from the example. Is this what you mean?

**Comment by ajvincent** [comment]
Yeah, that's what I meant, but then I reread your original comment... and both of us missed something.

When you invoked:
`var dryHandler = dryWetMB.getHandlerByName("dry", true);`

that code threw an exception.  The reason is an API change 5 months ago, and clearly not updated in the README.  The same would happen when you created the wetHandler.

Here's how it should read:
```
var wetHandler = dryWetMB.getHandlerByName("wet", { mustCreate: true });
var dryHandler = dryWetMB.getHandlerByName("dry", { mustCreate: true });
// continue as normal
```

**Comment by ajvincent** [comment]
(caused by #91 specifically)

**Comment by LucaFranceschini** [comment]
A-ha! That worked, thanks fro prompt help.

I'll play with this a bit and see if I can use this.

**Comment by ajvincent** [comment]
This needs to stay open:  I have to actually fix the README... :-)

**Comment by ajvincent** [comment]
While we're on the subject of outdated readme's, check out https://ajvincent.github.io/es-membrane/gui
