### ISSUE TITLE
Copy & rewrite TC39 talk for general audience

### ISSUE THREAD

**Issue by ajvincent** [ajvincent/es-membrane#184]
To-do list starting Nov. 28, 2018:
- [x] Rebuild layout: canvases should be 16:9 for easy conversion to YouTube video (#189)
- [x] Add 2-D canvas support for slides using [FabricJS](http://fabricjs.com)
- [x] Remove HTML slide mode
- [ ] Implement full-screen mode for the canvases
- [ ] Integrate audio recordings, Popcorn.js

**Comment by cliveb** [comment]
@ajvincent Very much looking forward to your TC39 talk for a general audience. Quite a few of us (http://clive.tries.fed.wiki/view/federated-wiki-already-met-ocap) are trying to figure out how to implement SES after Dr. SES and es-membranes seems to be key. Happy to be a reader / reviewier should you need one (I doubt you do).

**Comment by ajvincent** [comment]
@cliveb on the contrary, I think having reviewers would be critically important.  After all, I can get lost in jargon sometimes.  So having your help would be greatly welcomed.

**Comment by ajvincent** [comment]
Help wanted on the framework for the presentation (not on the text of the presentation:  that's on me.)

**Comment by cliveb** [comment]
@ajvincent I've watched erights videos and reprised his PhD. His Sept talk to the Node security group is typical. It can be hard for folks to grip the significance because material can look academic. Thus the general audience talk needs to set up what is to be said and also be succinct I can take a shot at an outline through this approach angle? http://clive.tries.fed.wiki/view/observable-membrane (slow load server in Singapore).

**Comment by ajvincent** [comment]
Clive, if you want to help in an immediate and meaningful way, I have a need for SVG-based audio controls, similar in appearance (and bindable) to Firefox's audio player controls but with a "expand to fullscreen" button.  I'm very rusty with SVG, so if you're good with it or can spare the time to find an open-source SVG controls set, I'd be quite happy.

**Comment by ajvincent** [comment]
https://ajvincent.github.io/es-membrane/concepts/

**Comment by cliveb** [comment]
Uncertain: these buttons in svg?
https://support.mozilla.org/en-US/kb/html5-audio-and-video-firefox#w_audio-and-video-controls

**Comment by ajvincent** [comment]
On second thought, this request I made for a SVG-based player skin is really a lot of work for minimal gain, so you should ignore it.  :-)  I was overthinking that aspect of it.  Sure, Firefox's audio controls fit very well and Google Chrome's don't, but that's not a good justification for replacing the controls altogether.

Sorry, Clive.  I was being obnoxious earlier on this point.

Regarding how you can contribute:  on this ticket, I don't think there's a really good spot just yet...

**Comment by ajvincent** [comment]
Overnight, I realized my presentation is going to be complex enough - and probably bloated enough, with the required libraries and all the audio files I intend to generate - that I need to move it to its own repository.  Plus, it doesn't make sense to force automated tests to rerun for checking in a new slide of my presentation, when I have dozens to do.

**Comment by ajvincent** [comment]
https://ajvincent.github.io/Membrane-concepts/
