### ISSUE TITLE
show and tell: simple module system

### ISSUE THREAD

**Issue by kumavis** [ajvincent/es-membrane#219]
I made a [toy module system](https://gist.github.com/kumavis/97d0e9f7d7506c9cda6734ea2a7ed97e) where each module's exports are imported via a membrane.

This is part of my research for [LavaMoat](https://github.com/lavamoat/overview) security tools.

**Comment by ajvincent** [comment]
That's fantastic... but what do you want me to do about it?  I don't yet see anything specific to fix for this project.

**Comment by kumavis** [comment]
no i just wanted to present it. thanks for `es-membrane`
