### ISSUE TITLE
Standard distortion type:  Wrap one Promise in another for safety

### ISSUE THREAD

**Issue by ajvincent** [ajvincent/es-membrane#228]
The es-membrane library can't currently inspect the return values of Promise instances.  (They're Promises.  We don't have their values.)

That said, we can write something like this before it gets through the membrane:

p = p.then(wrapResultAndReturn, wrapResultAndThrow);

**Comment by ajvincent** [comment]
Relates to #193, #179.

**Comment by ajvincent** [comment]
The object graph violation comes from `Bob.foo = await AliceProxy.foo`.  At this point, the membrane is no longer in play.

**Comment by ajvincent** [comment]
This is invalid.  It just works.

**Comment by cliveb** [comment]
@ajvincent Thanks for updating PR. I'm also following observable membrane progress, esp on this PR https://github.com/salesforce/observable-membrane/pull/48
